### ISSUE TITLE
Erase files after FLSCLR generation on windows broken

### ISSUE THREAD

**Issue by rfnoise** [opensatelliteproject/goesdump#30]
https://www.dropbox.com/s/0elpei8dtbiutro/demuxdump-1492397472.bin?dl=0

https://www.dropbox.com/s/771ko1szews8d0m/xrit_errors.log?dl=0

```
20:46:09 ERROR   Error processing image (SysExcpt) 1492486837-GOES 15-Special interest or unspecified: System.IO.FileNotFoundException: Could not find file 'F:\sw\goes_xrit_viewer\goes_xrit_viewer\bin\Debug\channels\Images\Area of Interest\gos15chnWV03rgnXXseg001res04dat107034209587.lrit'.
File name: 'F:\sw\goes_xrit_viewer\goes_xrit_viewer\bin\Debug\channels\Images\Area of Interest\gos15chnWV03rgnXXseg001res04dat107034209587.lrit'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.OpenRead(String path)
   at OpenSatelliteProject.Tools.FileParser.GetHeaderFromFile(String filename) in F:\sw\goes_xrit_viewer\goes_xrit_viewer\XRIT\Tools\FileParser.cs:line 13
   at OpenSatelliteProject.ImageTools.GenerateFullImage(OrganizerData data, Boolean crop) in F:\sw\goes_xrit_viewer\goes_xrit_viewer\XRIT\Tools\ImageTools.cs:line 105
   at OpenSatelliteProject.ImageManager.ThreadLoop() in F:\sw\goes_xrit_viewer\goes_xrit_viewer\GoesDecoder\ImageManager.cs:line 180

20:46:09 DEBUG   Starting Generation of Water Vapour for GOES 15-Special interest or unspecified-WV-1492486837.png.

20:46:09 ERROR   Error processing image (SysExcpt) 1492486837-GOES 15-Special interest or unspecified: System.IO.FileNotFoundException: Could not find file 'F:\sw\goes_xrit_viewer\goes_xrit_viewer\bin\Debug\channels\Images\Area of Interest\gos15chnWV03rgnXXseg001res04dat107034209587.lrit'.
File name: 'F:\sw\goes_xrit_viewer\goes_xrit_viewer\bin\Debug\channels\Images\Area of Interest\gos15chnWV03rgnXXseg001res04dat107034209587.lrit'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.OpenRead(String path)
   at OpenSatelliteProject.Tools.FileParser.GetHeaderFromFile(String filename) in F:\sw\goes_xrit_viewer\goes_xrit_viewer\XRIT\Tools\FileParser.cs:line 13
   at OpenSatelliteProject.ImageTools.GenerateFullImage(OrganizerData data, Boolean crop) in F:\sw\goes_xrit_viewer\goes_xrit_viewer\XRIT\Tools\ImageTools.cs:
```

**Comment by racerxdl** [comment]
So re-running on windows here didn't got any errors. That should probably be a concurrent error or a bug in WinAPI. I will check if I can reproduce it sometime, that type of bugs worry me about.

**Comment by racerxdl** [comment]
Ok so we figured out that it may happen when **xrit2pic** is running together. How didn't I saw the `FileNotFound` in the main exception? LOL
